version: "3"

services:

  nginx:
    image: nginx:1.21
    restart: unless-stopped
    container_name: nuxt_nginx
    depends_on:
      - nuxt
    expose:
      - 80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    environment:
        VIRTUAL_HOST: test2.devcod.io
        LETSENCRYPT_HOST: test2.devcod.io
        LETSENCRYPT_EMAIL: info@rogerca.com

  nuxt:
    container_name: nuxt_app
    build: .
    restart: always
    command:
      "npm run start"
    expose:
      - 3000

networks:
  default:
    external: true
    name: nginx-proxy